import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


ASTERISK_ETC = Path(os.getenv("ASTERISK_ETC", "/etc/asterisk"))
BACKUP_DIR = Path(os.getenv("BACKUP_DIR", "/backups"))


def digits_only(value: str) -> str:
    return re.sub(r"\D+", "", value or "")


def did_plus(value: str) -> str:
    raw = (value or "").strip().replace(" ", "").replace("-", "").replace("/", "")
    if raw.startswith("+"):
        return "+" + digits_only(raw)
    if raw.startswith("00"):
        return "+" + digits_only(raw[2:])
    if raw.startswith("0") and len(raw) > 1:
        return "+49" + digits_only(raw[1:])
    return "+" + digits_only(raw)


@dataclass
class RenderedConfig:
    pjsip: str
    extensions: str
    cdr: str
    cdr_csv: str
    logger: str
    unifi_summary: str
    security_notes: str


def load_state(store: Any) -> dict[str, Any]:
    settings = store.get_settings()
    numbers = [dict(row) for row in store.list_rows("numbers")]
    clients = [dict(row) for row in store.list_rows("clients")]
    routes_inbound = [dict(row) for row in store.list_rows("routes_inbound")]
    routes_outbound = [dict(row) for row in store.list_rows("routes_outbound")]
    return {
        "settings": settings,
        "numbers": numbers,
        "clients": clients,
        "routes_inbound": routes_inbound,
        "routes_outbound": routes_outbound,
    }


def render(store: Any) -> RenderedConfig:
    state = load_state(store)
    return RenderedConfig(
        pjsip=render_pjsip(state),
        extensions=render_extensions(state),
        cdr=render_cdr(),
        cdr_csv=render_cdr_csv(),
        logger=render_logger(),
        unifi_summary=render_unifi_summary(state),
        security_notes=render_security_notes(state),
    )


def render_pjsip(state: dict[str, Any]) -> str:
    settings = state["settings"]
    numbers = state["numbers"]
    clients = state["clients"]
    provider_name = settings["provider_display_name"]
    lines: list[str] = [
        "; ==============================================================================",
        "; ITSH Neumeier / neumeier.cloud",
        "; Generated by ITSH Neumeier Asterisk WebGUI AIO",
        f"; Date: {datetime.now().isoformat(timespec='seconds')}",
        f"; Provider profile: {provider_name}",
        "; ==============================================================================",
        "",
        "[global]",
        "type=global",
        "user_agent=ITSH-Asterisk-WebGUI-AIO",
        "endpoint_identifier_order=ip,username,anonymous",
        "unidentified_request_count=3",
        "unidentified_request_period=60",
        "unidentified_request_prune_interval=30",
        "",
        "[transport-udp]",
        "type=transport",
        f"protocol={settings.get('provider_transport', 'udp')}",
        "bind=0.0.0.0:5060",
    ]
    if settings.get("external_signaling_address"):
        lines.append(f"external_signaling_address={settings['external_signaling_address']}")
    if settings.get("external_media_address"):
        lines.append(f"external_media_address={settings['external_media_address']}")
    if settings.get("local_net"):
        lines.append(f"local_net={settings['local_net']}")
    lines += [
        "",
        "; ------------------------------------------------------------------------------",
        "; UniFi Talk Gateway",
        "; ------------------------------------------------------------------------------",
        "[unifi-talk]",
        "type=endpoint",
        "transport=transport-udp",
        "context=from-unifi",
        "identify_by=ip",
        "disallow=all",
        "allow=alaw,ulaw",
        "aors=unifi-talk",
        "direct_media=no",
        "rtp_symmetric=yes",
        "force_rport=yes",
        "rewrite_contact=yes",
        "trust_id_inbound=yes",
        "send_pai=yes",
        "send_rpid=yes",
        f"from_domain={settings['asterisk_ip']}",
        "dtmf_mode=rfc4733",
        "",
        "[unifi-talk]",
        "type=aor",
        f"contact=sip:{settings['unifi_ip']}:{settings['unifi_port']}",
        "qualify_frequency=30",
        "",
        "[unifi-talk-identify]",
        "type=identify",
        "endpoint=unifi-talk",
        f"match={settings['unifi_ip']}/32",
        "",
        "; ------------------------------------------------------------------------------",
        f"; Provider inbound: {provider_name}",
        "; ------------------------------------------------------------------------------",
        "[provider-in]",
        "type=endpoint",
        "transport=transport-udp",
        "context=from-leonet",
        "identify_by=ip",
        "disallow=all",
        "allow=alaw,ulaw",
        "dtmf_mode=rfc4733",
        "direct_media=no",
        "rtp_symmetric=yes",
        "force_rport=yes",
        "rewrite_contact=yes",
        "trust_id_inbound=yes",
        "send_pai=yes",
        "send_rpid=yes",
        f"from_domain={settings['provider_from_domain']}",
        "",
        "[leonet-in](provider-in)",
        "",
    ]

    match_ip = settings.get("provider_match_ip", "")
    if match_ip:
        lines += [
            "[provider-in-identify]",
            "type=identify",
            "endpoint=provider-in",
            f"match={match_ip}",
            "",
            "[leonet-in-identify]",
            "type=identify",
            "endpoint=leonet-in",
            f"match={match_ip}",
            "",
        ]

    for index, number in enumerate(numbers, start=1):
        username = number["sip_username"]
        password = number["sip_password"]
        lines += [
            "; ------------------------------------------------------------------------------",
            f"; Provider outbound {index} - {number['did_plus']} - {provider_name}",
            "; ------------------------------------------------------------------------------",
            f"[leonet-out-{index}-auth]",
            "type=auth",
            "auth_type=userpass",
            f"username={username}",
            f"password={password}",
            "",
            f"[leonet-out-{index}-aor]",
            "type=aor",
            f"contact={settings['provider_server_uri']}",
            "qualify_frequency=30",
            "",
            f"[leonet-out-{index}]",
            "type=endpoint",
            "transport=transport-udp",
            "context=from-leonet",
            "disallow=all",
            "allow=alaw,ulaw",
            f"aors=leonet-out-{index}-aor",
            f"outbound_auth=leonet-out-{index}-auth",
            f"from_user={username}",
            f"from_domain={settings['provider_from_domain']}",
            "dtmf_mode=rfc4733",
            "direct_media=no",
            "rtp_symmetric=yes",
            "force_rport=yes",
            "rewrite_contact=yes",
            "trust_id_inbound=yes",
            "send_pai=yes",
            "send_rpid=yes",
            "timers=yes",
        ]
        if settings.get("provider_outbound_proxy"):
            lines.append(f"outbound_proxy={settings['provider_outbound_proxy']}")
        lines.append("")
        if settings.get("provider_use_registration", "yes") == "yes":
            lines += [
                f"[leonet-out-{index}-reg]",
                "type=registration",
                "transport=transport-udp",
                f"outbound_auth=leonet-out-{index}-auth",
                f"server_uri={settings['provider_server_uri']}",
                f"client_uri=sip:{username}@{settings['provider_from_domain']}",
                f"contact_user={username}",
                "retry_interval=60",
                "forbidden_retry_interval=300",
                "expiration=300",
                "line=yes",
                f"endpoint=leonet-out-{index}",
            ]
            if settings.get("provider_outbound_proxy"):
                lines.append(f"outbound_proxy={settings['provider_outbound_proxy']}")
            lines.append("")

    enabled_clients = [client for client in clients if int(client["enabled"]) == 1]
    if enabled_clients:
        lines += [
            "; ------------------------------------------------------------------------------",
            "; Interne SIP-Clients / Nebenstellen",
            "; ------------------------------------------------------------------------------",
            "",
        ]
        for client in enabled_clients:
            allow = client["audio_codecs"] or "alaw,ulaw"
            if int(client["video_enabled"]) and client["video_codecs"]:
                allow = f"{allow},{client['video_codecs']}"
            lines += [
                f"; Client {client['client_id']} - {client['name']} - Typ: {client['client_type']}",
                f"[{client['client_id']}-auth]",
                "type=auth",
                "auth_type=userpass",
                f"username={client['sip_username']}",
                f"password={client['sip_password']}",
                "",
                f"[{client['client_id']}-aor]",
                "type=aor",
                "max_contacts=1",
                "remove_existing=yes",
                "qualify_frequency=30",
                "",
                f"[{client['client_id']}]",
                "type=endpoint",
                "transport=transport-udp",
                "context=from-internal-client",
                "disallow=all",
                f"allow={allow}",
                f"auth={client['client_id']}-auth",
                f"aors={client['client_id']}-aor",
                f"callerid=\"{client['name']}\" <{client['extension']}>",
                "dtmf_mode=rfc4733",
                "direct_media=no",
                "rtp_symmetric=yes",
                "force_rport=yes",
                "rewrite_contact=yes",
                "trust_id_inbound=yes",
                "send_pai=yes",
                "send_rpid=yes",
                "max_audio_streams=1",
                f"max_video_streams={1 if int(client['video_enabled']) else 0}",
                f"set_var=CLIENT_CALLERID={client['caller_id_plus'] or client['extension']}",
                f"set_var=CLIENT_EXTENSION={client['extension']}",
                f"set_var=CLIENT_ID={client['client_id']}",
                "",
            ]
            if client["ip_acl"]:
                lines += [
                    f"[{client['client_id']}-identify]",
                    "type=identify",
                    f"endpoint={client['client_id']}",
                    f"match={client['ip_acl']}",
                    "",
                ]
    return "\n".join(lines) + "\n"


def render_extensions(state: dict[str, Any]) -> str:
    settings = state["settings"]
    numbers = state["numbers"]
    clients = [client for client in state["clients"] if int(client["enabled"]) == 1]
    inbound_routes = state["routes_inbound"]
    outbound_routes = state["routes_outbound"]
    number_index = {number["id"]: index for index, number in enumerate(numbers, start=1)}
    default_number = numbers[0]
    lines = [
        "; ==============================================================================",
        "; ITSH Neumeier / neumeier.cloud",
        "; ITSH Neumeier Asterisk SIP-Trunk Management Dialplan",
        "; ==============================================================================",
        "",
        "[general]",
        "static=yes",
        "writeprotect=no",
        "clearglobalvars=no",
        "",
        "[from-leonet]",
        "exten => _X!,1,Gosub(route-leonet-in,s,1(${EXTEN}))",
        " same => n,Hangup()",
        "exten => _+X!,1,Gosub(route-leonet-in,s,1(${EXTEN}))",
        " same => n,Hangup()",
        "exten => _leoX!,1,Gosub(route-leonet-in,s,1(${EXTEN}))",
        " same => n,Hangup()",
        "",
        "[route-leonet-in]",
        "exten => s,1,NoOp(Inbound from provider raw DID: ${ARG1})",
        " same => n,Set(DID_NP=${FILTER(0-9,${ARG1})})",
        " same => n,GotoIf($[${LEN(${DID_NP})}=0]?no_did)",
        " same => n,Set(DID_PLUS=+${DID_NP})",
        " same => n,Set(CALLER_RAW=${CALLERID(num)})",
        " same => n,Set(CALLER_DIGITS=${FILTER(0-9,${CALLER_RAW})})",
        " same => n,Set(CALLER_PLUS=)",
        ' same => n,ExecIf($["${CALLER_DIGITS:0:1}"="0"]?Set(CALLER_PLUS=+49${CALLER_DIGITS:1}))',
        ' same => n,ExecIf($["${CALLER_DIGITS:0:2}"="49"]?Set(CALLER_PLUS=+${CALLER_DIGITS}))',
        " same => n,ExecIf($[${LEN(${CALLER_PLUS})}=0]?Set(CALLER_PLUS=${CALLER_RAW}))",
        " same => n,Set(CALLERID(num)=${CALLER_PLUS})",
        " same => n,Set(CALLERID(name)=${CALLER_PLUS})",
        " same => n,Set(CDR(userfield)=inbound:${DID_PLUS})",
        f" same => n,Set(PJSIP_HEADER(add,P-Asserted-Identity)=<sip:${{CALLER_PLUS}}@{settings['asterisk_ip']}>)",
        " same => n,Set(PJSIP_HEADER(add,X-UniFi-DID)=${DID_PLUS})",
        " same => n,Gosub(route-inbound-csv,s,1(${DID_PLUS},${DID_NP}))",
        " same => n,Hangup()",
        " same => n(no_did),Hangup(28)",
        "",
        "[route-inbound-csv]",
        "exten => s,1,NoOp(Inbound CSV route lookup DID ${ARG1} / ${ARG2})",
        " same => n,Set(ROUTE_DID_NP=${ARG2})",
        " same => n,GotoIf($[${DIALPLAN_EXISTS(route-inbound-csv,${ROUTE_DID_NP},1)}]?${ROUTE_DID_NP},1:default_unifi)",
        " same => n(default_unifi),Dial(PJSIP/${ROUTE_DID_NP}@unifi-talk,60)",
        " same => n,Return()",
        "",
        "[from-unifi]",
        "exten => _X!,1,Gosub(route-unifi-out,s,1(${EXTEN}))",
        " same => n,Hangup()",
        "exten => _+X!,1,Gosub(route-unifi-out,s,1(${EXTEN}))",
        " same => n,Hangup()",
        "",
        "[route-unifi-out]",
        "exten => s,1,NoOp(Outbound from UniFi raw target: ${ARG1}, caller: ${CALLERID(num)})",
        " same => n,Set(DEST_DIGITS=${FILTER(0-9,${ARG1})})",
        " same => n,GotoIf($[${LEN(${DEST_DIGITS})}=0]?bad_dest)",
        " same => n,Set(DEST_PLUS=+${DEST_DIGITS})",
        ' same => n,ExecIf($["${DEST_DIGITS:0:1}"="0"]?Set(DEST_PLUS=+49${DEST_DIGITS:1}))',
        " same => n,Set(CALLER_DIGITS=${FILTER(0-9,${CALLERID(num)})})",
        " same => n,Gosub(select-outbound-route,s,1(unifi,unifi-talk,${CALLER_DIGITS}))",
        " same => n,Set(CALLERID(num)=${SELECTED_CLI_PLUS})",
        " same => n,Set(CALLERID(name)=${SELECTED_CLI_PLUS})",
        " same => n,Set(CDR(userfield)=outbound:${SELECTED_CLI_PLUS}->${DEST_PLUS})",
        f" same => n,Set(PJSIP_HEADER(add,P-Asserted-Identity)=<sip:${{SELECTED_CLI_PLUS}}@{settings['provider_from_domain']}>)",
        " same => n,Dial(PJSIP/${DEST_PLUS}@${SELECTED_ENDPOINT},60)",
        " same => n,Hangup()",
        " same => n(bad_dest),Hangup(28)",
        "",
        "[from-internal-client]",
        "exten => _X!,1,Gosub(route-client-out,s,1(${EXTEN}))",
        " same => n,Hangup()",
        "exten => _+X!,1,Gosub(route-client-out,s,1(${EXTEN}))",
        " same => n,Hangup()",
        "include => internal-extensions",
        "",
        "[route-client-out]",
        "exten => s,1,NoOp(Outbound from SIP client ${CLIENT_ID} to ${ARG1})",
        " same => n,Set(DEST_DIGITS=${FILTER(0-9,${ARG1})})",
        " same => n,GotoIf($[${LEN(${DEST_DIGITS})}=0]?bad_dest)",
        " same => n,Set(DEST_PLUS=+${DEST_DIGITS})",
        ' same => n,ExecIf($["${DEST_DIGITS:0:1}"="0"]?Set(DEST_PLUS=+49${DEST_DIGITS:1}))',
        " same => n,Set(CALLER_DIGITS=${FILTER(0-9,${CALLERID(num)})})",
        " same => n,Gosub(select-outbound-route,s,1(client,${CLIENT_ID},${CALLER_DIGITS}))",
        " same => n,Set(CALLERID(num)=${SELECTED_CLI_PLUS})",
        " same => n,Set(CALLERID(name)=${SELECTED_CLI_PLUS})",
        " same => n,Set(CDR(userfield)=outbound:${SELECTED_CLI_PLUS}->${DEST_PLUS})",
        f" same => n,Set(PJSIP_HEADER(add,P-Asserted-Identity)=<sip:${{SELECTED_CLI_PLUS}}@{settings['provider_from_domain']}>)",
        " same => n,Dial(PJSIP/${DEST_PLUS}@${SELECTED_ENDPOINT},60)",
        " same => n,Hangup()",
        " same => n(bad_dest),Hangup(28)",
        "",
        "[internal-extensions]",
    ]
    for client in clients:
        lines += [
            f"exten => {client['extension']},1,NoOp(Internal call to {client['name']} / {client['client_id']})",
            f" same => n,Dial(PJSIP/{client['client_id']},45)",
            " same => n,Hangup()",
            "",
        ]

    lines += [
        "[select-outbound-route]",
        "exten => s,1,NoOp(Select outbound route for ${ARG1}/${ARG2}, caller ${ARG3})",
        " same => n,Set(SELECTED_ENDPOINT=leonet-out-1)",
        f" same => n,Set(SELECTED_USER={default_number['sip_username']})",
        f" same => n,Set(SELECTED_CLI_PLUS={default_number['did_plus']})",
        " same => n,Set(ROUTE_SOURCE_TYPE=${ARG1})",
        " same => n,Set(ROUTE_SOURCE_ID=${ARG2})",
        " same => n,Set(ROUTE_CALLER_DIGITS=${ARG3})",
        " same => n,GotoIf($[${DIALPLAN_EXISTS(select-outbound-csv,${ROUTE_SOURCE_TYPE}-${ROUTE_SOURCE_ID},1)}]?csv_route:default_route)",
        " same => n(default_route),Gosub(select-leonet-trunk,s,1(${ROUTE_CALLER_DIGITS}))",
        " same => n,Return()",
        " same => n(csv_route),Gosub(select-outbound-csv,${ROUTE_SOURCE_TYPE}-${ROUTE_SOURCE_ID},1)",
        " same => n,Return()",
        "",
        "[select-outbound-csv]",
        "exten => h,1,Return()",
        "",
        "[select-leonet-trunk]",
        "exten => s,1,NoOp(Select provider trunk for caller ${ARG1})",
        " same => n,Set(SELECTED_ENDPOINT=leonet-out-1)",
        f" same => n,Set(SELECTED_USER={default_number['sip_username']})",
        f" same => n,Set(SELECTED_CLI_PLUS={default_number['did_plus']})",
    ]
    for index, number in enumerate(numbers, start=1):
        digits = digits_only(number["did_plus"])
        lines += [
            f' same => n,ExecIf($["${{ARG1}}"="{digits}"]?Set(SELECTED_ENDPOINT=leonet-out-{index}))',
            f' same => n,ExecIf($["${{ARG1}}"="{digits}"]?Set(SELECTED_USER={number["sip_username"]}))',
            f' same => n,ExecIf($["${{ARG1}}"="{digits}"]?Set(SELECTED_CLI_PLUS={number["did_plus"]}))',
        ]
    lines += [" same => n,Return()", ""]

    if inbound_routes:
        lines += [
            "; ------------------------------------------------------------------------------",
            "; WebGUI Inbound Routing Overrides",
            "; ------------------------------------------------------------------------------",
        ]
        for route in inbound_routes:
            route_digits = digits_only(route["did_plus"])
            target = "PJSIP/${EXTEN}@unifi-talk"
            if route["target_type"] == "client":
                target = f"PJSIP/{route['target_id']}"
            elif route["target_type"] == "unifi":
                target = f"PJSIP/{route_digits}@unifi-talk"
            lines += [
                f"exten => {route_digits},1,NoOp(Web inbound route {route['did_plus']} -> {route['target_type']}/{route['target_id']})",
                f" same => n,Dial({target},{int(route['ring_seconds'])})",
                " same => n,Return()",
                "",
            ]

    if outbound_routes:
        lines += [
            "; ------------------------------------------------------------------------------",
            "; WebGUI Outbound Routing Overrides",
            "; ------------------------------------------------------------------------------",
        ]
        number_by_id = {number["id"]: number for number in numbers}
        for route in outbound_routes:
            number = number_by_id.get(route["number_id"], default_number)
            index = number_index.get(number["id"], 1)
            caller_id = route["caller_id_plus"] or number["did_plus"]
            lines += [
                f"exten => {route['source_type']}-{route['source_id']},1,NoOp(Web outbound route {route['source_type']}/{route['source_id']} -> leonet-out-{index} / {caller_id})",
                f" same => n,Set(SELECTED_ENDPOINT=leonet-out-{index})",
                f" same => n,Set(SELECTED_CLI_PLUS={caller_id})",
                f" same => n,Set(SELECTED_USER={number['sip_username']})",
                " same => n,Return()",
                "",
            ]
    return "\n".join(lines) + "\n"


def render_cdr() -> str:
    return """; ==============================================================================
; Generated by ITSH Neumeier Asterisk WebGUI AIO
; ==============================================================================

[general]
enable=yes
unanswered=yes
congestion=yes
endbeforehexten=no

"""


def render_cdr_csv() -> str:
    return """; ==============================================================================
; Generated by ITSH Neumeier Asterisk WebGUI AIO
; ==============================================================================

[csv]
usegmtime=no
loguniqueid=yes
loguserfield=yes
accountlogs=no

"""


def render_logger() -> str:
    return """; ==============================================================================
; Generated by ITSH Neumeier Asterisk WebGUI AIO
; ==============================================================================

[general]
dateformat=%F %T
queue_log=yes

[logfiles]
full => notice,warning,error,debug,verbose,dtmf
messages => notice,warning,error
console => notice,warning,error

"""


def render_unifi_summary(state: dict[str, Any]) -> str:
    settings = state["settings"]
    numbers = state["numbers"]
    main_digits = digits_only(numbers[0]["did_plus"]) if numbers else "491234567890"
    dids = "\n".join(f"  - {number['did_plus']}" for number in numbers)
    return f"""ITSH Neumeier / neumeier.cloud
UniFi Talk - Endeinrichtung / Custom SIP Provider
=================================================

Provider: Custom
Provider Name: LEONET-Transit-SIP-Trunk

Custom Fields:
  proxy: {settings['asterisk_ip']}:5060
  realm: {settings['asterisk_ip']}
  dtmfmode: rfc2833
  password: leer lassen
  register: false
  username: {main_digits}
  extension: auto_to_user
  sip_cid_type: rpid
  auth-username: leer lassen
  retry-seconds: 30
  expire-seconds: 120
  register-transport: udp

Phone Numbers:
{dids}

Advanced:
  IP Address Range: {settings['unifi_range']}

Port-Hinweis:
  UniFi Talk -> Asterisk: {settings['asterisk_ip']}:5060
  Asterisk -> UniFi Talk: {settings['unifi_ip']}:{settings['unifi_port']}
"""


def render_security_notes(state: dict[str, Any]) -> str:
    settings = state["settings"]
    return f"""ITSH Neumeier / neumeier.cloud
Asterisk SIP-Trunk Management IT-Grundsicherheit
================================================

Empfohlene Firewall-Regeln:
  SIP UDP/5060 nur von Provider-Netz und UniFi Talk erlauben.
  Provider-Netz: {settings.get('provider_match_ip') or '<manuell setzen>'}
  UniFi Talk:    {settings['unifi_ip']}/32

RTP:
  UDP/10000-20000 fuer benoetigte Gegenstellen erlauben.

Betrieb:
  asterisk -rx 'pjsip show endpoints'
  asterisk -rx 'pjsip show registrations'
  asterisk -rx 'pjsip show contacts'
"""


def apply_config(store: Any, reload_asterisk: bool = True) -> dict[str, str]:
    rendered = render(store)
    ASTERISK_ETC.mkdir(parents=True, exist_ok=True)
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = BACKUP_DIR / stamp
    backup_path.mkdir(parents=True, exist_ok=True)
    for filename in ("pjsip.conf", "extensions.conf", "cdr.conf", "cdr_csv.conf", "logger.conf"):
        source = ASTERISK_ETC / filename
        if source.exists():
            shutil.copy2(source, backup_path / filename)
    (ASTERISK_ETC / "pjsip.conf").write_text(rendered.pjsip, encoding="utf-8")
    (ASTERISK_ETC / "extensions.conf").write_text(rendered.extensions, encoding="utf-8")
    (ASTERISK_ETC / "cdr.conf").write_text(rendered.cdr, encoding="utf-8")
    (ASTERISK_ETC / "cdr_csv.conf").write_text(rendered.cdr_csv, encoding="utf-8")
    (ASTERISK_ETC / "logger.conf").write_text(rendered.logger, encoding="utf-8")
    (BACKUP_DIR / "unifi-talk-config-summary.txt").write_text(
        rendered.unifi_summary, encoding="utf-8"
    )
    (BACKUP_DIR / "itsh-astm-security-notes.txt").write_text(
        rendered.security_notes, encoding="utf-8"
    )
    reload_status = "skipped"
    if reload_asterisk:
        reload_status = reload()
    return {"backup": str(backup_path), "reload": reload_status}


def reload() -> str:
    commands = ["pjsip reload", "dialplan reload", "cdr reload", "logger reload"]
    outputs: list[str] = []
    for command in commands:
        try:
            result = subprocess.run(
                ["asterisk", "-rx", command],
                check=False,
                capture_output=True,
                text=True,
                timeout=15,
            )
            outputs.append((result.stdout or result.stderr or "").strip())
        except Exception as exc:
            outputs.append(f"{command}: {exc}")
    return "\n".join(output for output in outputs if output) or "ok"


def asterisk_status() -> str:
    try:
        result = subprocess.run(
            ["asterisk", "-rx", "pjsip show endpoints"],
            check=False,
            capture_output=True,
            text=True,
            timeout=15,
        )
        return (result.stdout or result.stderr or "").strip()
    except Exception as exc:
        return f"Asterisk status unavailable: {exc}"
